#!/usr/bin/env bash


OS_NAME="$(uname -s)"
case "${OS_NAME}" in
    Darwin*)
        realpath() {
            [[ $1 = /* ]] && echo "$1" || echo "${PWD}/${1#./}"
        }
    ;;
esac


SCRIPT_DIR=$(realpath "$(dirname "${0}")")
VENV_DIR=${SCRIPT_DIR}/.venv
USE_TEST_PYPI=0
POSITIONAL=()


usage() {
cat << EOF
Runs an example(s).

Usage:
    MINDSYNC_API_KEY=... MINDSYNC_BASE_URL=... ${0} EXAMPLE_NAME [EXAMPLE_NAME...]

Arguments:
    EXAMPLE_NAME   Example file name

Options:
    --help         Shows help message
EOF
}

# set -eux

while [ "${#}" -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            exit
        ;;

        *)
            POSITIONAL+=("${1}")
        ;;
    esac
    
   shift
done

if [ "${#POSITIONAL[@]}" -eq 0 ]; then
    usage
    exit 1
fi
# set -ex

if [ -d "${VENV_DIR}" ]; then
    source "${VENV_DIR}/bin/activate"
else
    python3 -m venv "${VENV_DIR}" && \
    source "${VENV_DIR}/bin/activate" && \
    pip3 install -r "${SCRIPT_DIR}/requirements.txt"
fi


for FN in "${POSITIONAL[@]}" ; do
    echo -e "\033[0;36mRunning ${FN}...\033[0m"
    python "${FN}"
done
